export { default as Home } from "./Home";
export { default as Movies } from "./Movies";
export { default as About } from "./About";
export { default as Favorite } from "./Favorite";
export { default as Newsletter } from "./Newsletter";
export { default as NotFound } from "./NotFound";
export { default as SinglePageError } from "./SinglePageError";
export { default as MovieDetails } from "./MovieDetails";
export { default as MovieDetail } from "./MovieDetails";
